# ::ILANG
# ::STATE{@SELF, role:把I-Lang更新频率同步成GitHub工作流}
# ::BOUNDARY{never:引入外部密钥 伪造检查成功}
import sys
from config import ROOT, load_config

def workflow():
    cfg = load_config()
    return '''# Generated by sync_workflow.py from .ilang/site.ilang
name: Refresh official VPS promotions
on:
  schedule:
    - cron: "CRON"
  workflow_dispatch:
  push:
    branches: [main]
    paths-ignore: ['data/**', 'site/**']
permissions:
  contents: write
concurrency:
  group: offer-refresh
  cancel-in-progress: false
jobs:
  refresh:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Check I-Lang schedule consistency
        run: python sync_workflow.py --check
      - name: Test data safety
        run: python -m unittest discover -s tests
      - name: Fetch official pages
        run: python scraper.py
      - name: Build static website
        run: python build.py
      - name: Commit verified results
        run: |
          git config user.name "vps-deals bot"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add data/offers.json site/
          if ! git diff --cached --quiet; then
            git commit -m "Refresh official sources and static pages"
            git push
          fi
      - name: Report source failures after publishing honest data
        run: python health.py
'''.replace('CRON',cfg['cron'])

if __name__ == '__main__':
    path = ROOT/'.github/workflows/update.yml'
    content = workflow()
    if '--check' in sys.argv:
        if not path.exists() or path.read_text(encoding='utf-8') != content:
            raise SystemExit('Run python sync_workflow.py and commit the updated workflow')
    else:
        path.parent.mkdir(parents=True,exist_ok=True)
        path.write_text(content,encoding='utf-8')
